data:
  path: "C:/Users/andre/proyecto_1PD/data/data.csv" 

preprocess:
  numeric: normalize
  categorical: onehot

split:
  train_size: 0.8

models:
  - linear_regression
  - random_forest
  - gradient_boosting

hyperparameters:
  random_forest:
    n_estimators: 100
    max_depth: 10
  gradient_boosting:
    learning_rate: 0.1
    n_estimators: 100

